-- ============================================================
-- Reconstructed DDL for schema 'ubec_main'
-- Source: comprehensive database documentation (structure only)
-- Generated by build_schema_from_doc.py
--
-- Version: 1.1.0  (2026-07-02)
-- Changelog:
--   1.1.0 — Added the element_type and token_code enum types, recovered after
--           a live sync failed with 'type "..." does not exist'. The source
--           documentation recorded the columns using them only as USER-DEFINED
--           and omitted the CREATE TYPE definitions, so the parser mapped those
--           columns to text. The enums themselves are now created up front
--           (idempotently) because the synchronizer casts to them explicitly.
--   1.0.0 — Initial reconstruction: 49 tables, 44 sequences, 17 FKs.
--
-- License (code): GNU AGPL v3.0
-- This project uses the services of Claude and Anthropic PBC to
-- inform our decisions and recommendations.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS "ubec_main";
SET search_path TO "ubec_main", public;

-- ------------------------------------------------------------
-- Enum types
-- ------------------------------------------------------------
-- These two enums were present in the original production database but were
-- NOT captured by the source documentation (the columns using them appear only
-- as USER-DEFINED, without their CREATE TYPE definitions). The synchronizer's
-- INSERTs cast to them explicitly ($n::element_type, $n::token_code), so the
-- types MUST exist or every write fails with 'type "..." does not exist'.
-- Values recovered from live sync parameters + canonical tokenomics:
--   element_type — lowercase elements as stored in PostgreSQL
--   token_code   — the four UBEC asset codes
-- Wrapped in idempotent DO/EXCEPTION blocks so re-applying the schema is safe.
DO $$ BEGIN
    CREATE TYPE "ubec_main"."element_type" AS ENUM ('air','water','earth','fire');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE "ubec_main"."token_code" AS ENUM ('UBEC','UBECrc','UBECgpi','UBECtt');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Sequences
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."account_order_positions_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."agent_activity_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."agent_benefit_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."agent_contribution_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."agent_holon_memberships_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."agents_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."api_rate_limits_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."asset_holder_analysis_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."asset_holders_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."bioregion_analysis_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."constraint_violations_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."distribution_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."distribution_state_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."distribution_transfers_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."holder_discovery_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."holonic_metrics_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."holons_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."liquidity_pool_owners_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."mutualism_relationships_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."orderbook_analytics_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."orderbook_snapshots_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."participants_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."reciprocity_transactions_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."regenerative_projects_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."scheduler_execution_log_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."scheduler_jobs_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."schema_migrations_migration_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."stellar_accounts_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."stellar_effects_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."stellar_offers_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."stellar_operations_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."stellar_transactions_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."sync_jobs_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."system_configuration_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."system_settings_setting_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."transfer_recommendations_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."transformation_phases_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."transformative_actions_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_audit_log_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_balances_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_distributions_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_holonic_metrics_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_reports_id_seq";
CREATE SEQUENCE IF NOT EXISTS "ubec_main"."ubec_sync_status_id_seq";

CREATE TABLE IF NOT EXISTS "ubec_main"."account_order_positions" (
    "id" integer NOT NULL DEFAULT nextval('account_order_positions_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "asset_code" text NOT NULL,
    "total_buy_orders" integer DEFAULT 0,
    "total_buy_volume" numeric(20,7) DEFAULT 0,
    "avg_buy_price" numeric(20,7),
    "total_sell_orders" integer DEFAULT 0,
    "total_sell_volume" numeric(20,7) DEFAULT 0,
    "avg_sell_price" numeric(20,7),
    "last_updated" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("account_id", "asset_code")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."agent_activity_history" (
    "id" integer NOT NULL DEFAULT nextval('agent_activity_history_id_seq'::regclass),
    "agent_id" integer NOT NULL,
    "activity_type" varchar(100) NOT NULL,
    "score_impact" numeric(10,4) DEFAULT 0,
    "timestamp" bigint NOT NULL,
    "details" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (("timestamp" > 0))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."agent_benefit_history" (
    "id" integer NOT NULL DEFAULT nextval('agent_benefit_history_id_seq'::regclass),
    "agent_id" integer NOT NULL,
    "benefit_type" varchar(100) NOT NULL,
    "amount" numeric(20,7) DEFAULT 0,
    "timestamp" bigint NOT NULL,
    "details" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (("timestamp" > 0))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."agent_contribution_history" (
    "id" integer NOT NULL DEFAULT nextval('agent_contribution_history_id_seq'::regclass),
    "agent_id" integer NOT NULL,
    "contribution_type" varchar(100) NOT NULL,
    "amount" numeric(20,7) DEFAULT 0,
    "timestamp" bigint NOT NULL,
    "details" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (("timestamp" > 0))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."agent_holon_memberships" (
    "id" integer NOT NULL DEFAULT nextval('agent_holon_memberships_id_seq'::regclass),
    "agent_id" integer NOT NULL,
    "holon_id" integer NOT NULL,
    "role_in_holon" varchar(100),
    "contribution_score" numeric(10,4) DEFAULT 0,
    "status" varchar(50) NOT NULL DEFAULT 'active'::character varying,
    "joined_at" timestamptz NOT NULL DEFAULT now(),
    "left_at" timestamptz,
    "metadata" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("agent_id", "holon_id"),
    CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."agents" (
    "id" integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass),
    "agent_id" varchar(56) NOT NULL,
    "participant_id" integer,
    "reputation_score" numeric(10,4) DEFAULT 0,
    "reciprocity_score" numeric(10,4) DEFAULT 0,
    "loyalty_tier" varchar(20) DEFAULT 'none'::character varying,
    "last_activity_at" timestamp,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "status" varchar(20) DEFAULT 'active'::character varying,
    "metrics" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("agent_id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."api_rate_limits" (
    "id" integer NOT NULL DEFAULT nextval('api_rate_limits_id_seq'::regclass),
    "api_name" varchar(50) NOT NULL,
    "rate_limit_remaining" integer,
    "rate_limit_limit" integer,
    "rate_limit_reset" integer,
    "last_updated" timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("api_name")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."asset_holder_analysis" (
    "id" integer NOT NULL DEFAULT nextval('asset_holder_analysis_id_seq'::regclass),
    "analysis_date" timestamp NOT NULL DEFAULT now(),
    "asset_code" varchar(12) NOT NULL,
    "asset_issuer" varchar(56) NOT NULL,
    "total_supply" numeric(18,8) NOT NULL,
    "total_holders" integer NOT NULL,
    "general_circulation" numeric(18,8),
    "stewardship_held" numeric(18,8),
    "administration_held" numeric(18,8),
    "general_pct" numeric(5,4),
    "stewardship_pct" numeric(5,4),
    "administration_pct" numeric(5,4),
    "is_compliant" boolean,
    "details" jsonb,
    "active_holders" integer NOT NULL DEFAULT 0,
    "new_holders_last_30_days" integer DEFAULT 0,
    "whale_concentration_percent" numeric(10,4),
    "gini_coefficient" numeric(10,8),
    "distribution_metrics" jsonb,
    PRIMARY KEY ("id"),
    CHECK ((total_holders >= 0)),
    CHECK ((total_supply > (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."asset_holders" (
    "id" integer NOT NULL DEFAULT nextval('asset_holders_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "asset_code" varchar(12) NOT NULL,
    "asset_issuer" varchar(56) NOT NULL,
    "balance" numeric(18,8) NOT NULL DEFAULT 0,
    "last_updated" timestamp NOT NULL DEFAULT now(),
    "classification" varchar(20),
    PRIMARY KEY ("id"),
    UNIQUE ("account_id", "asset_code", "asset_issuer"),
    CHECK ((balance >= (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."bioregion_analysis" (
    "id" integer NOT NULL DEFAULT nextval('bioregion_analysis_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "community_id" integer NOT NULL,
    "analysis_date" timestamptz DEFAULT now(),
    "source_type" varchar(20),
    "metadata" jsonb,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."constraint_violations" (
    "id" integer NOT NULL DEFAULT nextval('constraint_violations_id_seq'::regclass),
    "table_name" varchar(100) NOT NULL,
    "constraint_name" varchar(100) NOT NULL,
    "violation_data" jsonb,
    "error_message" text,
    "occurred_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."distribution_history" (
    "id" integer NOT NULL DEFAULT nextval('distribution_history_id_seq'::regclass),
    "check_date" timestamp NOT NULL DEFAULT now(),
    "asset_code" varchar(12) NOT NULL,
    "asset_issuer" varchar(56) NOT NULL,
    "general_balance" numeric(18,8) NOT NULL,
    "admin_balance" numeric(18,8) NOT NULL,
    "stewardship_balance" numeric(18,8) NOT NULL,
    "total_supply" numeric(18,8),
    "rebalance_needed" boolean NOT NULL,
    "transfers_initiated" integer DEFAULT 0,
    "total_transfer_amount" numeric(18,8) DEFAULT 0,
    "details" jsonb,
    "general_percentage" numeric(10,4),
    "admin_percentage" numeric(10,4),
    "stewardship_percentage" numeric(10,4),
    PRIMARY KEY ("id"),
    CHECK (((general_balance >= (0)::numeric) AND (admin_balance >= (0)::numeric) AND (stewardship_balance >= (0)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."distribution_state" (
    "id" integer NOT NULL DEFAULT nextval('distribution_state_id_seq'::regclass),
    "asset_code" varchar(12) NOT NULL,
    "category" varchar(50) NOT NULL,
    "current_amount" numeric(20,7) DEFAULT 0.0,
    "target_amount" numeric(20,7) DEFAULT 0.0,
    "target_percentage" numeric(5,2) NOT NULL,
    "actual_percentage" numeric(5,2) DEFAULT 0.0,
    "is_compliant" boolean DEFAULT true,
    "last_updated" timestamptz DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("asset_code", "category"),
    CHECK (((current_amount >= (0)::numeric) AND (target_amount >= (0)::numeric))),
    CHECK (((target_percentage >= (0)::numeric) AND (target_percentage <= (100)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."distribution_transfers" (
    "id" integer NOT NULL DEFAULT nextval('distribution_transfers_id_seq'::regclass),
    "tx_hash" text NOT NULL,
    "from_account" text NOT NULL,
    "to_account" text NOT NULL,
    "amount" numeric(20,7) NOT NULL,
    "asset_code" text NOT NULL,
    "asset_issuer" text NOT NULL,
    "ledger" integer,
    "memo" text,
    "network" text NOT NULL,
    "executed_at" timestamp NOT NULL DEFAULT now(),
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "notes" text,
    "recorded_by" text DEFAULT 'distribution_service'::text,
    PRIMARY KEY ("id"),
    UNIQUE ("tx_hash"),
    CHECK ((network = ANY (ARRAY['TESTNET'::text, 'MAINNET'::text]))),
    CHECK ((amount > (0)::numeric)),
    CHECK ((network = ANY (ARRAY['TESTNET'::text, 'MAINNET'::text])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."flow_transactions" (
    "transaction_id" varchar(64) NOT NULL,
    "asset_code" varchar(12) NOT NULL,
    "from_account" varchar(56) NOT NULL,
    "to_account" varchar(56) NOT NULL,
    "amount" numeric(20,7) NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    "memo" text,
    PRIMARY KEY ("transaction_id"),
    CHECK ((amount > (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."gateway_accounts" (
    "account_id" varchar(56) NOT NULL,
    "asset_code" varchar(12) NOT NULL,
    "balance" numeric(20,7) DEFAULT 0.0,
    "trustline_established" boolean DEFAULT false,
    "created_at" timestamptz DEFAULT now(),
    "last_activity" timestamptz DEFAULT now(),
    "transaction_count" integer DEFAULT 0,
    PRIMARY KEY ("account_id"),
    CHECK ((balance >= (0)::numeric)),
    CHECK ((transaction_count >= 0))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."holder_discovery_history" (
    "id" integer NOT NULL DEFAULT nextval('holder_discovery_history_id_seq'::regclass),
    "discovery_date" timestamp NOT NULL DEFAULT now(),
    "account_id" varchar(56) NOT NULL,
    "discovery_source" varchar(50) NOT NULL,
    "source_transaction_id" varchar(64),
    "initial_balance" numeric(18,8) DEFAULT 0,
    "is_new" boolean DEFAULT true,
    "added_to_tracking" boolean DEFAULT false,
    "metadata" jsonb,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."holonic_metrics" (
    "id" integer NOT NULL DEFAULT nextval('holonic_metrics_id_seq'::regclass),
    "evaluation_date" timestamptz NOT NULL DEFAULT now(),
    "autonomy_integration_score" numeric(5,4) NOT NULL DEFAULT 0,
    "multi_scale_score" numeric(5,4) NOT NULL DEFAULT 0,
    "regenerative_impact_score" numeric(5,4) NOT NULL DEFAULT 0,
    "network_contribution_score" numeric(5,4) NOT NULL DEFAULT 0,
    "ubuntu_alignment_score" numeric(5,4) NOT NULL DEFAULT 0,
    "composite_score" numeric(5,4) NOT NULL DEFAULT 0,
    "holonic_category" varchar(50) NOT NULL DEFAULT 'Observer'::character varying,
    "raw_metrics" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "evaluation_date_date" date NOT NULL,
    "account_id" varchar(56) NOT NULL,
    "confidence" numeric(10,6) DEFAULT 0.8,
    "calculation_mode" text DEFAULT 'transaction_based'::text,
    PRIMARY KEY ("id"),
    UNIQUE ("account_id", "evaluation_date"),
    CHECK (((autonomy_integration_score >= (0)::numeric) AND (autonomy_integration_score <= (1)::numeric))),
    CHECK (((composite_score >= (0)::numeric) AND (composite_score <= (1)::numeric))),
    CHECK (((holonic_category)::text = ANY ((ARRAY['Observer'::character varying, 'Participant'::character varying, 'Contributor'::character varying, 'Integrator'::character varying, 'Exemplar'::character varying])::text[]))),
    CHECK (((multi_scale_score >= (0)::numeric) AND (multi_scale_score <= (1)::numeric))),
    CHECK (((network_contribution_score >= (0)::numeric) AND (network_contribution_score <= (1)::numeric))),
    CHECK (((regenerative_impact_score >= (0)::numeric) AND (regenerative_impact_score <= (1)::numeric))),
    CHECK (((ubuntu_alignment_score >= (0)::numeric) AND (ubuntu_alignment_score <= (1)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."holons" (
    "id" integer NOT NULL DEFAULT nextval('holons_id_seq'::regclass),
    "holon_id" varchar(100) NOT NULL,
    "holon_name" varchar(255) NOT NULL,
    "holon_type" varchar(100) NOT NULL,
    "description" text,
    "parent_holon_id" integer,
    "metadata" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("holon_id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."liquidity_pool_owners" (
    "id" integer NOT NULL DEFAULT nextval('liquidity_pool_owners_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "liquidity_pool_id" varchar(64) NOT NULL,
    "shares" numeric(20,7) NOT NULL DEFAULT 0,
    "ownership_percentage" numeric(10,6) NOT NULL DEFAULT 0,
    "ubec_balance" numeric(20,7) NOT NULL DEFAULT 0,
    "element" text DEFAULT 'air',
    "token_code" text,
    "metadata" jsonb,
    "last_modified_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "sync_timestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "sync_status" varchar(20) DEFAULT 'synced'::character varying,
    PRIMARY KEY ("id"),
    UNIQUE ("account_id", "liquidity_pool_id"),
    CHECK (((ownership_percentage >= (0)::numeric) AND (ownership_percentage <= (100)::numeric))),
    CHECK ((shares >= (0)::numeric)),
    CHECK ((ubec_balance >= (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."liquidity_pools" (
    "id" varchar(64) NOT NULL,
    "asset_a_code" varchar(12) NOT NULL,
    "asset_a_issuer" varchar(56),
    "asset_b_code" varchar(12) NOT NULL,
    "asset_b_issuer" varchar(56),
    "pair" varchar(50) NOT NULL,
    "primary_element" text DEFAULT 'air',
    "token_code" text,
    "reserve_a" numeric(20,7) NOT NULL DEFAULT 0,
    "reserve_b" numeric(20,7) NOT NULL DEFAULT 0,
    "total_shares" numeric(20,7) NOT NULL DEFAULT 0,
    "balance" numeric(20,7) NOT NULL DEFAULT 0,
    "ubec_asset_position" char(1),
    "fee_bp" integer DEFAULT 30,
    "trustline_count" integer DEFAULT 0,
    "metadata" jsonb,
    "last_modified_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "sync_timestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "sync_status" varchar(20) DEFAULT 'synced'::character varying,
    PRIMARY KEY ("id"),
    CHECK ((ubec_asset_position = ANY (ARRAY['a'::bpchar, 'b'::bpchar]))),
    CHECK ((balance >= (0)::numeric)),
    CHECK (((fee_bp >= 0) AND (fee_bp <= 10000))),
    CHECK (((reserve_a >= (0)::numeric) AND (reserve_b >= (0)::numeric))),
    CHECK ((total_shares >= (0)::numeric)),
    CHECK ((trustline_count >= 0))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."monitored_accounts" (
    "account_id" varchar(56) NOT NULL,
    "account_type" varchar(20) NOT NULL,
    "account_name" varchar(100),
    "description" text,
    "monitored_since" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "is_active" boolean DEFAULT true,
    "metadata" jsonb DEFAULT '{}'::jsonb,
    "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("account_id"),
    CHECK (((account_type)::text = ANY ((ARRAY['general'::character varying, 'administration'::character varying, 'stewardship'::character varying])::text[]))),
    CHECK (((account_id)::text ~ '^G[A-Z0-9]{55}$'::text)),
    CHECK (((account_name IS NULL) OR (length((account_name)::text) > 0)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."mutualism_relationships" (
    "id" integer NOT NULL DEFAULT nextval('mutualism_relationships_id_seq'::regclass),
    "asset_code" varchar(12) NOT NULL,
    "account_a" varchar(56) NOT NULL,
    "account_b" varchar(56) NOT NULL,
    "interaction_count" integer DEFAULT 0,
    "mutual_benefit_score" numeric(5,4) DEFAULT 0.0,
    "relationship_strength" numeric(5,4) DEFAULT 0.0,
    "last_interaction" timestamptz DEFAULT now(),
    "first_interaction" timestamptz DEFAULT now(),
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("asset_code", "account_a", "account_b"),
    CHECK ((interaction_count >= 0)),
    CHECK (((mutual_benefit_score >= (0)::numeric) AND (mutual_benefit_score <= (1)::numeric))),
    CHECK (((relationship_strength >= (0)::numeric) AND (relationship_strength <= (1)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."orderbook_analytics" (
    "id" integer NOT NULL DEFAULT nextval('orderbook_analytics_id_seq'::regclass),
    "asset_code" text NOT NULL,
    "analysis_time" timestamptz NOT NULL DEFAULT now(),
    "total_liquidity" numeric(20,7),
    "buy_pressure" numeric(10,4),
    "sell_pressure" numeric(10,4),
    "market_depth_score" numeric(10,4),
    "price_stability_score" numeric(10,4),
    "top_10_buyers_volume" numeric(20,7),
    "top_10_sellers_volume" numeric(20,7),
    "unique_buyers" integer,
    "unique_sellers" integer,
    "metrics" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("asset_code", "analysis_time")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."orderbook_snapshots" (
    "id" integer NOT NULL DEFAULT nextval('orderbook_snapshots_id_seq'::regclass),
    "asset_code" text NOT NULL,
    "counter_asset" varchar(12) NOT NULL,
    "snapshot_time" timestamptz NOT NULL DEFAULT now(),
    "best_bid" numeric(20,7),
    "best_ask" numeric(20,7),
    "spread_bps" integer,
    "bid_depth_total" numeric(20,7),
    "ask_depth_total" numeric(20,7),
    "bid_levels" integer,
    "ask_levels" integer,
    "raw_data" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("asset_code", "counter_asset", "snapshot_time")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."participants" (
    "id" integer NOT NULL DEFAULT nextval('participants_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "account_type" varchar(50) NOT NULL,
    "account_label" varchar(100),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("account_id"),
    CHECK (((account_type)::text = ANY ((ARRAY['general'::character varying, 'administration'::character varying, 'stewardship'::character varying, 'issuer'::character varying, 'other'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."reciprocity_transactions" (
    "id" integer NOT NULL DEFAULT nextval('reciprocity_transactions_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "transaction_type" varchar(20) NOT NULL,
    "amount" numeric(18,8) NOT NULL,
    "reason" text,
    "source" varchar(50),
    "context" jsonb,
    "created_at" timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (((transaction_type)::text = ANY ((ARRAY['credit'::character varying, 'debit'::character varying, 'adjustment'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."regenerative_projects" (
    "id" integer NOT NULL DEFAULT nextval('regenerative_projects_id_seq'::regclass),
    "agent_id" integer NOT NULL,
    "project_name" varchar(255) NOT NULL,
    "description" text,
    "project_type" varchar(100) NOT NULL,
    "verification_status" varchar(50) DEFAULT 'unverified'::character varying,
    "verification_date" timestamptz,
    "impact_metrics" jsonb,
    "metadata" jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (((verification_status)::text = ANY ((ARRAY['unverified'::character varying, 'pending'::character varying, 'verified'::character varying, 'rejected'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."scheduler_execution_log" (
    "id" integer NOT NULL DEFAULT nextval('scheduler_execution_log_id_seq'::regclass),
    "job_name" varchar(100) NOT NULL,
    "executed_at" timestamptz NOT NULL DEFAULT now(),
    "duration_ms" integer,
    "success" boolean NOT NULL,
    "error_message" text,
    "error_traceback" text,
    "created_at" timestamptz DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."scheduler_jobs" (
    "id" integer NOT NULL DEFAULT nextval('scheduler_jobs_id_seq'::regclass),
    "job_name" varchar(100) NOT NULL,
    "schedule_interval" varchar(50) NOT NULL,
    "next_run" timestamptz NOT NULL,
    "last_run" timestamptz,
    "job_function" text NOT NULL,
    "parameters" jsonb,
    "enabled" boolean DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("job_name"),
    CHECK ((next_run > created_at))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."schema_migrations" (
    "migration_id" integer NOT NULL DEFAULT nextval('schema_migrations_migration_id_seq'::regclass),
    "migration_name" varchar(255) NOT NULL,
    "applied_at" timestamptz NOT NULL DEFAULT now(),
    "applied_by" varchar(100) NOT NULL,
    "description" text,
    "checksum" varchar(64),
    "execution_time_ms" integer,
    "status" varchar(20) NOT NULL DEFAULT 'completed'::character varying,
    "error_message" text,
    "rollback_script" text,
    PRIMARY KEY ("migration_id"),
    UNIQUE ("migration_name"),
    CHECK (((status)::text = ANY ((ARRAY['completed'::character varying, 'failed'::character varying, 'rolled_back'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."stellar_accounts" (
    "id" integer NOT NULL DEFAULT nextval('stellar_accounts_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "primary_element" text,
    "token_holdings" text[],
    "sequence" bigint,
    "subentry_count" integer DEFAULT 0,
    "inflation_destination" varchar(56),
    "home_domain" varchar(255),
    "thresholds" jsonb,
    "flags" jsonb,
    "signers" jsonb,
    "created_at" timestamptz,
    "last_modified_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "last_activity_at" timestamptz,
    "sync_status" varchar(20) DEFAULT 'pending'::character varying,
    "sync_cursor" varchar(100),
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("account_id"),
    CHECK ((length((account_id)::text) = 56))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."stellar_effects" (
    "id" integer NOT NULL DEFAULT nextval('stellar_effects_id_seq'::regclass),
    "effect_id" varchar(100) NOT NULL,
    "operation_id" varchar(100) NOT NULL,
    "effect_element" text,
    "type" varchar(50) NOT NULL,
    "account" varchar(56),
    "amount" numeric(20,7),
    "asset_type" varchar(20),
    "asset_code" text,
    "asset_issuer" varchar(56),
    "details" jsonb,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("effect_id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."stellar_offers" (
    "id" integer NOT NULL DEFAULT nextval('stellar_offers_id_seq'::regclass),
    "offer_id" bigint NOT NULL,
    "seller_account" varchar(56) NOT NULL,
    "selling_asset" text,
    "buying_asset" varchar(12) NOT NULL,
    "amount" numeric(20,7) NOT NULL,
    "price" numeric(20,7) NOT NULL,
    "price_r_n" integer,
    "price_r_d" integer,
    "side" varchar(4) NOT NULL,
    "is_passive" boolean DEFAULT false,
    "last_modified_ledger" bigint,
    "last_modified_time" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "status" varchar(20) DEFAULT 'active'::character varying,
    PRIMARY KEY ("id"),
    UNIQUE ("offer_id"),
    CHECK (((side)::text = ANY ((ARRAY['buy'::character varying, 'sell'::character varying])::text[]))),
    CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'filled'::character varying, 'cancelled'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."stellar_operations" (
    "id" integer NOT NULL DEFAULT nextval('stellar_operations_id_seq'::regclass),
    "operation_id" varchar(100) NOT NULL,
    "transaction_hash" varchar(64) NOT NULL,
    "operation_element" text,
    "asset_code" text,
    "type" text NOT NULL,
    "type_i" integer,
    "source_account" varchar(56),
    "amount" numeric(20,7),
    "asset_type" varchar(20),
    "asset_issuer" varchar(56),
    "from_account" varchar(56),
    "to_account" varchar(56),
    "details" jsonb,
    "created_at" timestamptz NOT NULL,
    "metadata" jsonb,
    "exchange_source_asset" varchar(12),
    "exchange_source_amount" numeric(18,8),
    "exchange_dest_asset" varchar(12),
    "exchange_dest_amount" numeric(18,8),
    PRIMARY KEY ("id"),
    UNIQUE ("operation_id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."stellar_transactions" (
    "id" integer NOT NULL DEFAULT nextval('stellar_transactions_id_seq'::regclass),
    "transaction_hash" varchar(64) NOT NULL,
    "ledger_sequence" bigint NOT NULL,
    "primary_element" text,
    "involves_tokens" text[],
    "source_account" varchar(56) NOT NULL,
    "source_account_sequence" bigint,
    "fee_charged" bigint,
    "max_fee" bigint,
    "operation_count" integer,
    "time_bounds" jsonb,
    "memo_type" varchar(20),
    "memo" varchar(255),
    "successful" boolean DEFAULT true,
    "result_code" text,
    "result_xdr" text,
    "created_at" timestamptz NOT NULL,
    "ledger_close_time" timestamptz,
    "metadata" jsonb,
    "ledger" bigint,
    PRIMARY KEY ("id"),
    UNIQUE ("transaction_hash")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."sync_jobs" (
    "id" integer NOT NULL DEFAULT nextval('sync_jobs_id_seq'::regclass),
    "job_type" varchar(50) NOT NULL,
    "schedule_interval" interval NOT NULL,
    "last_run" timestamptz,
    "next_run" timestamptz NOT NULL,
    "enabled" boolean DEFAULT true,
    "parameters" jsonb,
    "last_status" varchar(20),
    "error_message" text,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."sync_status" (
    "account_id" varchar(56) NOT NULL,
    "last_sync" timestamptz NOT NULL DEFAULT now(),
    "last_block_height" bigint,
    "last_ledger_sequence" bigint,
    "last_transaction_id" varchar(64),
    "sync_count" integer DEFAULT 0,
    "status" varchar(20) DEFAULT 'active'::character varying,
    "error_count" integer DEFAULT 0,
    "last_error" text,
    "last_error_at" timestamptz,
    PRIMARY KEY ("account_id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."system_configuration" (
    "id" integer NOT NULL DEFAULT nextval('system_configuration_id_seq'::regclass),
    "parameter_name" varchar(100) NOT NULL,
    "parameter_value" text NOT NULL,
    "parameter_type" varchar(20) DEFAULT 'string'::character varying,
    "description" text,
    "is_sensitive" boolean DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("parameter_name"),
    CHECK (((parameter_type)::text = ANY ((ARRAY['string'::character varying, 'number'::character varying, 'boolean'::character varying, 'json'::character varying, 'address'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."system_settings" (
    "setting_id" integer NOT NULL DEFAULT nextval('system_settings_setting_id_seq'::regclass),
    "setting_key" varchar(100) NOT NULL,
    "setting_value" text NOT NULL,
    "setting_type" varchar(20) DEFAULT 'string'::character varying,
    "description" text,
    "category" varchar(50) DEFAULT 'general'::character varying,
    "is_active" boolean DEFAULT true,
    "is_encrypted" boolean DEFAULT false,
    "created_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now(),
    "created_by" varchar(100),
    "updated_by" varchar(100),
    PRIMARY KEY ("setting_id"),
    UNIQUE ("setting_key"),
    CHECK (((setting_type)::text = ANY ((ARRAY['string'::character varying, 'integer'::character varying, 'float'::character varying, 'boolean'::character varying, 'json'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."transfer_recommendations" (
    "id" integer NOT NULL DEFAULT nextval('transfer_recommendations_id_seq'::regclass),
    "recommendation_date" timestamp NOT NULL DEFAULT now(),
    "asset_code" varchar(12) NOT NULL,
    "asset_issuer" varchar(56) NOT NULL,
    "from_account_type" varchar(50) NOT NULL,
    "to_account_type" varchar(50) NOT NULL,
    "amount" numeric(18,8) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'pending'::character varying,
    "status_message" text,
    "transaction_hash" varchar(64),
    "actual_amount" numeric(18,8),
    "priority" integer DEFAULT 5,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "completed_at" timestamp,
    PRIMARY KEY ("id"),
    CHECK ((amount > (0)::numeric)),
    CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."transformation_phases" (
    "id" integer NOT NULL DEFAULT nextval('transformation_phases_id_seq'::regclass),
    "phase_id" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "start_date" timestamptz NOT NULL,
    "end_date" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "target_outcomes" text[] DEFAULT '{}',
    "key_indicators" jsonb DEFAULT '{}'::jsonb,
    "participating_agents" text[] DEFAULT '{}',
    "actions_completed" integer DEFAULT 0,
    "total_ubectt_distributed" numeric(20,7) DEFAULT 0.0,
    "phase_momentum" numeric(5,4) DEFAULT 0.0,
    "is_active" boolean DEFAULT true,
    "completion_percentage" numeric(5,2) DEFAULT 0.0,
    "metadata" jsonb DEFAULT '{}'::jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("phase_id"),
    CHECK ((actions_completed >= 0)),
    CHECK (((completion_percentage >= (0)::numeric) AND (completion_percentage <= (100)::numeric))),
    CHECK (((phase_momentum >= (0)::numeric) AND (phase_momentum <= (1)::numeric))),
    CHECK ((total_ubectt_distributed >= (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."transformative_actions" (
    "id" integer NOT NULL DEFAULT nextval('transformative_actions_id_seq'::regclass),
    "action_id" varchar(255) NOT NULL,
    "agent_id" varchar(56) NOT NULL,
    "action_type" text NOT NULL,
    "description" text NOT NULL,
    "impact_scale" text NOT NULL,
    "timestamp" timestamptz NOT NULL DEFAULT now(),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "direct_beneficiaries" integer DEFAULT 0,
    "indirect_reach" integer DEFAULT 0,
    "regeneration_score" numeric(5,4) DEFAULT 0.0,
    "catalytic_multiplier" numeric(5,4) DEFAULT 1.0,
    "verified" boolean DEFAULT false,
    "verifier_ids" text[] DEFAULT '{}',
    "evidence_urls" text[] DEFAULT '{}',
    "verification_count" integer,
    "ubectt_awarded" numeric(20,7) DEFAULT 0.0,
    "distribution_tx_hash" varchar(64),
    "reward_calculated_at" timestamptz,
    "reward_distributed_at" timestamptz,
    "tags" text[] DEFAULT '{}',
    "related_actions" text[] DEFAULT '{}',
    "metadata" jsonb DEFAULT '{}'::jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("action_id"),
    CHECK (((catalytic_multiplier >= (1)::numeric) AND (catalytic_multiplier <= (10)::numeric))),
    CHECK ((direct_beneficiaries >= 0)),
    CHECK ((indirect_reach >= 0)),
    CHECK (((regeneration_score >= (0)::numeric) AND (regeneration_score <= (1)::numeric))),
    CHECK ((ubectt_awarded >= (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_audit_log" (
    "id" integer NOT NULL DEFAULT nextval('ubec_audit_log_id_seq'::regclass),
    "element" text,
    "token_code" text,
    "entity_type" varchar(50) NOT NULL,
    "entity_id" varchar(100) NOT NULL,
    "audit_type" varchar(50) NOT NULL,
    "status" varchar(20) NOT NULL,
    "is_valid" boolean DEFAULT true,
    "is_anomaly" boolean DEFAULT false,
    "anomaly_type" varchar(50),
    "severity" varchar(20),
    "audit_details" jsonb,
    "validation_rules" jsonb,
    "violations" jsonb,
    "audited_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "auditor" varchar(100),
    "metadata" jsonb,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_balances" (
    "id" integer NOT NULL DEFAULT nextval('ubec_balances_id_seq'::regclass),
    "account_id" varchar(56) NOT NULL,
    "token_code" text NOT NULL,
    "element" text NOT NULL,
    "balance" numeric(20,7) NOT NULL DEFAULT 0,
    "buying_liabilities" numeric(20,7) DEFAULT 0,
    "selling_liabilities" numeric(20,7) DEFAULT 0,
    "limit_amount" numeric(20,7),
    "is_authorized" boolean DEFAULT false,
    "is_authorized_to_maintain_liabilities" boolean DEFAULT false,
    "is_clawback_enabled" boolean DEFAULT false,
    "distribution_category" text,
    "last_modified_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "sync_timestamp" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("account_id", "token_code"),
    CHECK ((balance >= (0)::numeric))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_distributions" (
    "id" integer NOT NULL DEFAULT nextval('ubec_distributions_id_seq'::regclass),
    "token_code" text NOT NULL,
    "element" text NOT NULL,
    "category" text NOT NULL,
    "target_percentage" numeric(5,2) NOT NULL,
    "current_percentage" numeric(5,2) NOT NULL,
    "current_amount" numeric(20,7) NOT NULL,
    "total_supply" numeric(20,7) NOT NULL,
    "is_compliant" boolean DEFAULT true,
    "deviation" numeric(5,2) DEFAULT 0,
    "snapshot_time" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "last_rebalance" timestamptz,
    "next_check" timestamptz,
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    CHECK (((current_percentage >= (0)::numeric) AND (current_percentage <= (100)::numeric))),
    CHECK (((target_percentage >= (0)::numeric) AND (target_percentage <= (100)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_holonic_metrics" (
    "id" integer NOT NULL DEFAULT nextval('ubec_holonic_metrics_id_seq'::regclass),
    "account_id" varchar(56),
    "element" text,
    "principle" text NOT NULL,
    "score" numeric(5,4) NOT NULL,
    "raw_value" numeric(20,7),
    "normalized_value" numeric(5,4),
    "health_status" text,
    "assessment_details" jsonb,
    "calculation_method" varchar(100),
    "data_points" integer,
    "confidence_level" numeric(5,4),
    "calculated_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "valid_until" timestamptz,
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    CHECK (((normalized_value IS NULL) OR ((normalized_value >= (0)::numeric) AND (normalized_value <= (1)::numeric)))),
    CHECK (((score >= (0)::numeric) AND (score <= (1)::numeric)))
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_reports" (
    "id" integer NOT NULL DEFAULT nextval('ubec_reports_id_seq'::regclass),
    "element" text,
    "token_code" text,
    "report_type" varchar(50) NOT NULL,
    "title" varchar(255) NOT NULL,
    "summary" text,
    "content" jsonb NOT NULL,
    "generated_by" varchar(100),
    "report_period_start" timestamptz,
    "report_period_end" timestamptz,
    "status" varchar(20) DEFAULT 'draft'::character varying,
    "generated_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "published_at" timestamptz,
    "file_path" varchar(500),
    "file_format" varchar(20),
    "metadata" jsonb,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ubec_main"."ubec_sync_status" (
    "id" integer NOT NULL DEFAULT nextval('ubec_sync_status_id_seq'::regclass),
    "element" text,
    "token_code" text,
    "sync_type" varchar(50) NOT NULL,
    "status" varchar(20) NOT NULL,
    "cursor" varchar(100),
    "last_sync_time" timestamptz,
    "next_sync_time" timestamptz,
    "records_synced" integer DEFAULT 0,
    "errors_encountered" integer DEFAULT 0,
    "duration_ms" integer,
    "sync_details" jsonb,
    "error_log" jsonb,
    "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
    "metadata" jsonb,
    PRIMARY KEY ("id"),
    UNIQUE ("element", "token_code", "sync_type")
);

-- Foreign keys (added after all tables exist)
ALTER TABLE "ubec_main"."account_order_positions" ADD FOREIGN KEY ("account_id") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."agent_activity_history" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."agents" ("id");
ALTER TABLE "ubec_main"."agent_benefit_history" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."agents" ("id");
ALTER TABLE "ubec_main"."agent_contribution_history" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."agents" ("id");
ALTER TABLE "ubec_main"."agent_holon_memberships" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."agents" ("id");
ALTER TABLE "ubec_main"."agent_holon_memberships" ADD FOREIGN KEY ("holon_id") REFERENCES "ubec_main"."holons" ("id");
ALTER TABLE "ubec_main"."holons" ADD FOREIGN KEY ("parent_holon_id") REFERENCES "ubec_main"."holons" ("id");
ALTER TABLE "ubec_main"."liquidity_pool_owners" ADD FOREIGN KEY ("account_id") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."liquidity_pool_owners" ADD FOREIGN KEY ("liquidity_pool_id") REFERENCES "ubec_main"."liquidity_pools" ("id");
ALTER TABLE "ubec_main"."regenerative_projects" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."agents" ("id");
ALTER TABLE "ubec_main"."stellar_effects" ADD FOREIGN KEY ("operation_id") REFERENCES "ubec_main"."stellar_operations" ("operation_id");
ALTER TABLE "ubec_main"."stellar_offers" ADD FOREIGN KEY ("seller_account") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."stellar_operations" ADD FOREIGN KEY ("transaction_hash") REFERENCES "ubec_main"."stellar_transactions" ("transaction_hash");
ALTER TABLE "ubec_main"."stellar_transactions" ADD FOREIGN KEY ("source_account") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."transformative_actions" ADD FOREIGN KEY ("agent_id") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."ubec_balances" ADD FOREIGN KEY ("account_id") REFERENCES "ubec_main"."stellar_accounts" ("account_id");
ALTER TABLE "ubec_main"."ubec_holonic_metrics" ADD FOREIGN KEY ("account_id") REFERENCES "ubec_main"."stellar_accounts" ("account_id");

-- Secondary indexes (btree/gin)
CREATE INDEX IF NOT EXISTS "ix_account_order_positions_account_id" ON "ubec_main"."account_order_positions" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_account_order_positions_asset_code" ON "ubec_main"."account_order_positions" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_account_order_positions_asset_code_total_buy_volume" ON "ubec_main"."account_order_positions" USING btree ("asset_code", "total_buy_volume");
CREATE INDEX IF NOT EXISTS "ix_account_order_positions_asset_code_total_sell_volume" ON "ubec_main"."account_order_positions" USING btree ("asset_code", "total_sell_volume");
CREATE INDEX IF NOT EXISTS "ix_account_order_positions_last_updated" ON "ubec_main"."account_order_positions" USING btree ("last_updated");
CREATE INDEX IF NOT EXISTS "ix_agent_activity_history_agent_id" ON "ubec_main"."agent_activity_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_activity_history_agent_id" ON "ubec_main"."agent_activity_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_activity_history_timestamp" ON "ubec_main"."agent_activity_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_activity_history_activity_type" ON "ubec_main"."agent_activity_history" USING btree ("activity_type");
CREATE INDEX IF NOT EXISTS "ix_agent_activity_history_timestamp" ON "ubec_main"."agent_activity_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_benefit_history_agent_id" ON "ubec_main"."agent_benefit_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_benefit_history_agent_id" ON "ubec_main"."agent_benefit_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_benefit_history_timestamp" ON "ubec_main"."agent_benefit_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_benefit_history_benefit_type" ON "ubec_main"."agent_benefit_history" USING btree ("benefit_type");
CREATE INDEX IF NOT EXISTS "ix_agent_benefit_history_timestamp" ON "ubec_main"."agent_benefit_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_contribution_history_agent_id" ON "ubec_main"."agent_contribution_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_contribution_history_agent_id" ON "ubec_main"."agent_contribution_history" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_contribution_history_timestamp" ON "ubec_main"."agent_contribution_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_contribution_history_contribution_type" ON "ubec_main"."agent_contribution_history" USING btree ("contribution_type");
CREATE INDEX IF NOT EXISTS "ix_agent_contribution_history_timestamp" ON "ubec_main"."agent_contribution_history" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_agent_id" ON "ubec_main"."agent_holon_memberships" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_holon_id" ON "ubec_main"."agent_holon_memberships" USING btree ("holon_id");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_agent_id" ON "ubec_main"."agent_holon_memberships" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_holon_id" ON "ubec_main"."agent_holon_memberships" USING btree ("holon_id");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_status" ON "ubec_main"."agent_holon_memberships" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_agent_holon_memberships_status" ON "ubec_main"."agent_holon_memberships" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_agents_agent_id" ON "ubec_main"."agents" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_agents_status" ON "ubec_main"."agents" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_api_rate_limits_api_name" ON "ubec_main"."api_rate_limits" USING btree ("api_name");
CREATE INDEX IF NOT EXISTS "ix_asset_holder_analysis_asset_code_asset_issuer" ON "ubec_main"."asset_holder_analysis" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_asset_holder_analysis_is_compliant" ON "ubec_main"."asset_holder_analysis" USING btree ("is_compliant");
CREATE INDEX IF NOT EXISTS "ix_asset_holder_analysis_analysis_date" ON "ubec_main"."asset_holder_analysis" USING btree ("analysis_date");
CREATE INDEX IF NOT EXISTS "ix_asset_holder_analysis_asset_code_asset_issuer" ON "ubec_main"."asset_holder_analysis" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_asset_holder_analysis_analysis_date" ON "ubec_main"."asset_holder_analysis" USING btree ("analysis_date");
CREATE INDEX IF NOT EXISTS "ix_asset_holders_account_id" ON "ubec_main"."asset_holders" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_asset_holders_asset_code_asset_issuer" ON "ubec_main"."asset_holders" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_asset_holders_balance" ON "ubec_main"."asset_holders" USING btree ("balance");
CREATE INDEX IF NOT EXISTS "ix_asset_holders_last_updated" ON "ubec_main"."asset_holders" USING btree ("last_updated");
CREATE INDEX IF NOT EXISTS "ix_constraint_violations_table_name" ON "ubec_main"."constraint_violations" USING btree ("table_name");
CREATE INDEX IF NOT EXISTS "ix_constraint_violations_occurred_at" ON "ubec_main"."constraint_violations" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_asset_code_asset_issuer" ON "ubec_main"."distribution_history" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_check_date" ON "ubec_main"."distribution_history" USING btree ("check_date");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_details" ON "ubec_main"."distribution_history" USING gin ("details");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_rebalance_needed" ON "ubec_main"."distribution_history" USING btree ("rebalance_needed");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_asset_code_asset_issuer" ON "ubec_main"."distribution_history" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_check_date" ON "ubec_main"."distribution_history" USING btree ("check_date");
CREATE INDEX IF NOT EXISTS "ix_distribution_history_rebalance_needed" ON "ubec_main"."distribution_history" USING btree ("rebalance_needed");
CREATE INDEX IF NOT EXISTS "ix_distribution_state_asset_code" ON "ubec_main"."distribution_state" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_distribution_state_category" ON "ubec_main"."distribution_state" USING btree ("category");
CREATE INDEX IF NOT EXISTS "ix_distribution_state_is_compliant" ON "ubec_main"."distribution_state" USING btree ("is_compliant");
CREATE INDEX IF NOT EXISTS "ix_distribution_state_last_updated" ON "ubec_main"."distribution_state" USING btree ("last_updated");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_asset_code_asset_issuer" ON "ubec_main"."distribution_transfers" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_asset_code_executed_at" ON "ubec_main"."distribution_transfers" USING btree ("asset_code", "executed_at");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_executed_at" ON "ubec_main"."distribution_transfers" USING btree ("executed_at");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_from_account" ON "ubec_main"."distribution_transfers" USING btree ("from_account");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_network" ON "ubec_main"."distribution_transfers" USING btree ("network");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_to_account" ON "ubec_main"."distribution_transfers" USING btree ("to_account");
CREATE INDEX IF NOT EXISTS "ix_distribution_transfers_tx_hash" ON "ubec_main"."distribution_transfers" USING btree ("tx_hash");
CREATE INDEX IF NOT EXISTS "ix_flow_transactions_asset_code" ON "ubec_main"."flow_transactions" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_flow_transactions_asset_code_created_at" ON "ubec_main"."flow_transactions" USING btree ("asset_code", "created_at");
CREATE INDEX IF NOT EXISTS "ix_flow_transactions_created_at" ON "ubec_main"."flow_transactions" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_flow_transactions_from_account" ON "ubec_main"."flow_transactions" USING btree ("from_account");
CREATE INDEX IF NOT EXISTS "ix_flow_transactions_to_account" ON "ubec_main"."flow_transactions" USING btree ("to_account");
CREATE INDEX IF NOT EXISTS "ix_gateway_accounts_asset_code" ON "ubec_main"."gateway_accounts" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_gateway_accounts_last_activity" ON "ubec_main"."gateway_accounts" USING btree ("last_activity");
CREATE INDEX IF NOT EXISTS "ix_gateway_accounts_trustline_established" ON "ubec_main"."gateway_accounts" USING btree ("trustline_established");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_account_id" ON "ubec_main"."holonic_metrics" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_calculation_mode" ON "ubec_main"."holonic_metrics" USING btree ("calculation_mode");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_holonic_category" ON "ubec_main"."holonic_metrics" USING btree ("holonic_category");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_composite_score" ON "ubec_main"."holonic_metrics" USING btree ("composite_score");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_confidence" ON "ubec_main"."holonic_metrics" USING btree ("confidence");
CREATE INDEX IF NOT EXISTS "ix_holonic_metrics_evaluation_date" ON "ubec_main"."holonic_metrics" USING btree ("evaluation_date");
CREATE INDEX IF NOT EXISTS "ix_holons_holon_id" ON "ubec_main"."holons" USING btree ("holon_id");
CREATE INDEX IF NOT EXISTS "ix_holons_holon_type" ON "ubec_main"."holons" USING btree ("holon_type");
CREATE INDEX IF NOT EXISTS "ix_holons_parent_holon_id" ON "ubec_main"."holons" USING btree ("parent_holon_id");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_account_id" ON "ubec_main"."liquidity_pool_owners" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_account_id_ubec_balance" ON "ubec_main"."liquidity_pool_owners" USING btree ("account_id", "ubec_balance");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_account_id_token_code" ON "ubec_main"."liquidity_pool_owners" USING btree ("account_id", "token_code");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_ubec_balance" ON "ubec_main"."liquidity_pool_owners" USING btree ("ubec_balance");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_element" ON "ubec_main"."liquidity_pool_owners" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_last_modified_at" ON "ubec_main"."liquidity_pool_owners" USING btree ("last_modified_at");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_liquidity_pool_id" ON "ubec_main"."liquidity_pool_owners" USING btree ("liquidity_pool_id");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_sync_status" ON "ubec_main"."liquidity_pool_owners" USING btree ("sync_status");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_sync_timestamp" ON "ubec_main"."liquidity_pool_owners" USING btree ("sync_timestamp");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pool_owners_token_code" ON "ubec_main"."liquidity_pool_owners" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_asset_a_code_asset_a_issuer" ON "ubec_main"."liquidity_pools" USING btree ("asset_a_code", "asset_a_issuer");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_asset_b_code_asset_b_issuer" ON "ubec_main"."liquidity_pools" USING btree ("asset_b_code", "asset_b_issuer");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_balance" ON "ubec_main"."liquidity_pools" USING btree ("balance");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_primary_element" ON "ubec_main"."liquidity_pools" USING btree ("primary_element");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_last_modified_at" ON "ubec_main"."liquidity_pools" USING btree ("last_modified_at");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_pair" ON "ubec_main"."liquidity_pools" USING btree ("pair");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_sync_status" ON "ubec_main"."liquidity_pools" USING btree ("sync_status");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_sync_timestamp" ON "ubec_main"."liquidity_pools" USING btree ("sync_timestamp");
CREATE INDEX IF NOT EXISTS "ix_liquidity_pools_token_code" ON "ubec_main"."liquidity_pools" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_monitored_accounts_is_active" ON "ubec_main"."monitored_accounts" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "ix_monitored_accounts_account_id_account_type" ON "ubec_main"."monitored_accounts" USING btree ("account_id", "account_type");
CREATE INDEX IF NOT EXISTS "ix_monitored_accounts_account_type" ON "ubec_main"."monitored_accounts" USING btree ("account_type");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_account_a" ON "ubec_main"."mutualism_relationships" USING btree ("account_a");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_account_b" ON "ubec_main"."mutualism_relationships" USING btree ("account_b");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_asset_code" ON "ubec_main"."mutualism_relationships" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_asset_code_relationship_strength" ON "ubec_main"."mutualism_relationships" USING btree ("asset_code", "relationship_strength");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_last_interaction" ON "ubec_main"."mutualism_relationships" USING btree ("last_interaction");
CREATE INDEX IF NOT EXISTS "ix_mutualism_relationships_relationship_strength" ON "ubec_main"."mutualism_relationships" USING btree ("relationship_strength");
CREATE INDEX IF NOT EXISTS "ix_orderbook_analytics_asset_code" ON "ubec_main"."orderbook_analytics" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_orderbook_analytics_asset_code_analysis_time" ON "ubec_main"."orderbook_analytics" USING btree ("asset_code", "analysis_time");
CREATE INDEX IF NOT EXISTS "ix_orderbook_analytics_analysis_time" ON "ubec_main"."orderbook_analytics" USING btree ("analysis_time");
CREATE INDEX IF NOT EXISTS "ix_orderbook_snapshots_asset_code_counter_asset" ON "ubec_main"."orderbook_snapshots" USING btree ("asset_code", "counter_asset");
CREATE INDEX IF NOT EXISTS "ix_orderbook_snapshots_asset_code_snapshot_time" ON "ubec_main"."orderbook_snapshots" USING btree ("asset_code", "snapshot_time");
CREATE INDEX IF NOT EXISTS "ix_orderbook_snapshots_snapshot_time" ON "ubec_main"."orderbook_snapshots" USING btree ("snapshot_time");
CREATE INDEX IF NOT EXISTS "ix_participants_account_id" ON "ubec_main"."participants" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_participants_account_id" ON "ubec_main"."participants" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_participants_is_active" ON "ubec_main"."participants" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "ix_participants_account_type" ON "ubec_main"."participants" USING btree ("account_type");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_account_id" ON "ubec_main"."reciprocity_transactions" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_created_at" ON "ubec_main"."reciprocity_transactions" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_transaction_type" ON "ubec_main"."reciprocity_transactions" USING btree ("transaction_type");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_account_id" ON "ubec_main"."reciprocity_transactions" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_created_at" ON "ubec_main"."reciprocity_transactions" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_source" ON "ubec_main"."reciprocity_transactions" USING btree ("source");
CREATE INDEX IF NOT EXISTS "ix_reciprocity_transactions_transaction_type" ON "ubec_main"."reciprocity_transactions" USING btree ("transaction_type");
CREATE INDEX IF NOT EXISTS "ix_regenerative_projects_agent_id" ON "ubec_main"."regenerative_projects" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_regenerative_projects_project_type" ON "ubec_main"."regenerative_projects" USING btree ("project_type");
CREATE INDEX IF NOT EXISTS "ix_regenerative_projects_verification_status" ON "ubec_main"."regenerative_projects" USING btree ("verification_status");
CREATE INDEX IF NOT EXISTS "ix_regenerative_projects_verification_status" ON "ubec_main"."regenerative_projects" USING btree ("verification_status");
CREATE INDEX IF NOT EXISTS "ix_scheduler_execution_log_executed_at" ON "ubec_main"."scheduler_execution_log" USING btree ("executed_at");
CREATE INDEX IF NOT EXISTS "ix_scheduler_execution_log_job_name" ON "ubec_main"."scheduler_execution_log" USING btree ("job_name");
CREATE INDEX IF NOT EXISTS "ix_scheduler_execution_log_success" ON "ubec_main"."scheduler_execution_log" USING btree ("success");
CREATE INDEX IF NOT EXISTS "ix_scheduler_jobs_enabled" ON "ubec_main"."scheduler_jobs" USING btree ("enabled");
CREATE INDEX IF NOT EXISTS "ix_scheduler_jobs_next_run" ON "ubec_main"."scheduler_jobs" USING btree ("next_run");
CREATE INDEX IF NOT EXISTS "ix_schema_migrations_applied_at" ON "ubec_main"."schema_migrations" USING btree ("applied_at");
CREATE INDEX IF NOT EXISTS "ix_schema_migrations_status" ON "ubec_main"."schema_migrations" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_stellar_accounts_account_id" ON "ubec_main"."stellar_accounts" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_stellar_accounts_last_activity_at" ON "ubec_main"."stellar_accounts" USING btree ("last_activity_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_accounts_created_at" ON "ubec_main"."stellar_accounts" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_accounts_primary_element" ON "ubec_main"."stellar_accounts" USING btree ("primary_element");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_account" ON "ubec_main"."stellar_effects" USING btree ("account");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_asset_code" ON "ubec_main"."stellar_effects" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_created_at" ON "ubec_main"."stellar_effects" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_effect_element" ON "ubec_main"."stellar_effects" USING btree ("effect_element");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_effect_id" ON "ubec_main"."stellar_effects" USING btree ("effect_id");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_operation_id" ON "ubec_main"."stellar_effects" USING btree ("operation_id");
CREATE INDEX IF NOT EXISTS "ix_stellar_effects_type" ON "ubec_main"."stellar_effects" USING btree ("type");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_selling_asset_buying_asset" ON "ubec_main"."stellar_offers" USING btree ("selling_asset", "buying_asset");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_seller_account" ON "ubec_main"."stellar_offers" USING btree ("seller_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_selling_asset" ON "ubec_main"."stellar_offers" USING btree ("selling_asset");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_side" ON "ubec_main"."stellar_offers" USING btree ("side");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_status" ON "ubec_main"."stellar_offers" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_selling_asset_status" ON "ubec_main"."stellar_offers" USING btree ("selling_asset", "status");
CREATE INDEX IF NOT EXISTS "ix_stellar_offers_last_modified_time" ON "ubec_main"."stellar_offers" USING btree ("last_modified_time");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_asset_code" ON "ubec_main"."stellar_operations" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_created_at" ON "ubec_main"."stellar_operations" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_operation_element" ON "ubec_main"."stellar_operations" USING btree ("operation_element");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_from_account" ON "ubec_main"."stellar_operations" USING btree ("from_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_operation_id" ON "ubec_main"."stellar_operations" USING btree ("operation_id");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_to_account" ON "ubec_main"."stellar_operations" USING btree ("to_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_transaction_hash" ON "ubec_main"."stellar_operations" USING btree ("transaction_hash");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_type" ON "ubec_main"."stellar_operations" USING btree ("type");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_asset_code_from_account_to_account_created_at" ON "ubec_main"."stellar_operations" USING btree ("asset_code", "from_account", "to_account", "created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_asset_code" ON "ubec_main"."stellar_operations" USING btree ("asset_code");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_created_at" ON "ubec_main"."stellar_operations" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_from_account" ON "ubec_main"."stellar_operations" USING btree ("from_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_asset_code_from_account" ON "ubec_main"."stellar_operations" USING btree ("asset_code", "from_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_source_account" ON "ubec_main"."stellar_operations" USING btree ("source_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_to_account" ON "ubec_main"."stellar_operations" USING btree ("to_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_operations_asset_code_to_account" ON "ubec_main"."stellar_operations" USING btree ("asset_code", "to_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_created_at" ON "ubec_main"."stellar_transactions" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_primary_element" ON "ubec_main"."stellar_transactions" USING btree ("primary_element");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_transaction_hash" ON "ubec_main"."stellar_transactions" USING btree ("transaction_hash");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_ledger_sequence" ON "ubec_main"."stellar_transactions" USING btree ("ledger_sequence");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_source_account" ON "ubec_main"."stellar_transactions" USING btree ("source_account");
CREATE INDEX IF NOT EXISTS "ix_stellar_transactions_involves_tokens" ON "ubec_main"."stellar_transactions" USING gin ("involves_tokens");
CREATE INDEX IF NOT EXISTS "ix_system_configuration_parameter_name" ON "ubec_main"."system_configuration" USING btree ("parameter_name");
CREATE INDEX IF NOT EXISTS "ix_system_configuration_parameter_type" ON "ubec_main"."system_configuration" USING btree ("parameter_type");
CREATE INDEX IF NOT EXISTS "ix_system_configuration_parameter_name" ON "ubec_main"."system_configuration" USING btree ("parameter_name");
CREATE INDEX IF NOT EXISTS "ix_system_settings_category" ON "ubec_main"."system_settings" USING btree ("category");
CREATE INDEX IF NOT EXISTS "ix_system_settings_setting_key" ON "ubec_main"."system_settings" USING btree ("setting_key");
CREATE INDEX IF NOT EXISTS "ix_system_settings_setting_key_is_active" ON "ubec_main"."system_settings" USING btree ("setting_key", "is_active");
CREATE INDEX IF NOT EXISTS "ix_system_settings_setting_key" ON "ubec_main"."system_settings" USING btree ("setting_key");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_asset_code_asset_issuer" ON "ubec_main"."transfer_recommendations" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_recommendation_date" ON "ubec_main"."transfer_recommendations" USING btree ("recommendation_date");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_priority" ON "ubec_main"."transfer_recommendations" USING btree ("priority");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_status" ON "ubec_main"."transfer_recommendations" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_asset_code_asset_issuer" ON "ubec_main"."transfer_recommendations" USING btree ("asset_code", "asset_issuer");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_created_at" ON "ubec_main"."transfer_recommendations" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_recommendation_date" ON "ubec_main"."transfer_recommendations" USING btree ("recommendation_date");
CREATE INDEX IF NOT EXISTS "ix_transfer_recommendations_status" ON "ubec_main"."transfer_recommendations" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_is_active" ON "ubec_main"."transformation_phases" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_participating_agents" ON "ubec_main"."transformation_phases" USING gin ("participating_agents");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_completion_percentage" ON "ubec_main"."transformation_phases" USING btree ("completion_percentage");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_end_date" ON "ubec_main"."transformation_phases" USING btree ("end_date");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_metadata" ON "ubec_main"."transformation_phases" USING gin ("metadata");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_phase_momentum" ON "ubec_main"."transformation_phases" USING btree ("phase_momentum");
CREATE INDEX IF NOT EXISTS "ix_transformation_phases_start_date" ON "ubec_main"."transformation_phases" USING btree ("start_date");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_agent_id" ON "ubec_main"."transformative_actions" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_agent_id_timestamp" ON "ubec_main"."transformative_actions" USING btree ("agent_id", "timestamp");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_ubectt_awarded" ON "ubec_main"."transformative_actions" USING btree ("ubectt_awarded");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_catalytic_multiplier" ON "ubec_main"."transformative_actions" USING btree ("catalytic_multiplier");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_metadata" ON "ubec_main"."transformative_actions" USING gin ("metadata");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_regeneration_score" ON "ubec_main"."transformative_actions" USING btree ("regeneration_score");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_impact_scale" ON "ubec_main"."transformative_actions" USING btree ("impact_scale");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_tags" ON "ubec_main"."transformative_actions" USING gin ("tags");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_timestamp" ON "ubec_main"."transformative_actions" USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_action_type" ON "ubec_main"."transformative_actions" USING btree ("action_type");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_action_type_verified" ON "ubec_main"."transformative_actions" USING btree ("action_type", "verified");
CREATE INDEX IF NOT EXISTS "ix_transformative_actions_verified" ON "ubec_main"."transformative_actions" USING btree ("verified");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_is_anomaly" ON "ubec_main"."ubec_audit_log" USING btree ("is_anomaly");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_element" ON "ubec_main"."ubec_audit_log" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_entity_type_entity_id" ON "ubec_main"."ubec_audit_log" USING btree ("entity_type", "entity_id");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_status" ON "ubec_main"."ubec_audit_log" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_audited_at" ON "ubec_main"."ubec_audit_log" USING btree ("audited_at");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_token_code" ON "ubec_main"."ubec_audit_log" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_ubec_audit_log_audit_type" ON "ubec_main"."ubec_audit_log" USING btree ("audit_type");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_account_id" ON "ubec_main"."ubec_balances" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_balance" ON "ubec_main"."ubec_balances" USING btree ("balance");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_distribution_category" ON "ubec_main"."ubec_balances" USING btree ("distribution_category");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_element" ON "ubec_main"."ubec_balances" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_last_modified_at" ON "ubec_main"."ubec_balances" USING btree ("last_modified_at");
CREATE INDEX IF NOT EXISTS "ix_ubec_balances_token_code" ON "ubec_main"."ubec_balances" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_ubec_distributions_category" ON "ubec_main"."ubec_distributions" USING btree ("category");
CREATE INDEX IF NOT EXISTS "ix_ubec_distributions_is_compliant" ON "ubec_main"."ubec_distributions" USING btree ("is_compliant");
CREATE INDEX IF NOT EXISTS "ix_ubec_distributions_element" ON "ubec_main"."ubec_distributions" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_distributions_snapshot_time" ON "ubec_main"."ubec_distributions" USING btree ("snapshot_time");
CREATE INDEX IF NOT EXISTS "ix_ubec_distributions_token_code" ON "ubec_main"."ubec_distributions" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_account_id" ON "ubec_main"."ubec_holonic_metrics" USING btree ("account_id");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_calculated_at" ON "ubec_main"."ubec_holonic_metrics" USING btree ("calculated_at");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_element" ON "ubec_main"."ubec_holonic_metrics" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_health_status" ON "ubec_main"."ubec_holonic_metrics" USING btree ("health_status");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_principle" ON "ubec_main"."ubec_holonic_metrics" USING btree ("principle");
CREATE INDEX IF NOT EXISTS "ix_ubec_holonic_metrics_score" ON "ubec_main"."ubec_holonic_metrics" USING btree ("score");
CREATE INDEX IF NOT EXISTS "ix_ubec_reports_element" ON "ubec_main"."ubec_reports" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_reports_generated_at" ON "ubec_main"."ubec_reports" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "ix_ubec_reports_status" ON "ubec_main"."ubec_reports" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_ubec_reports_token_code" ON "ubec_main"."ubec_reports" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_ubec_reports_report_type" ON "ubec_main"."ubec_reports" USING btree ("report_type");
CREATE INDEX IF NOT EXISTS "ix_ubec_sync_status_element" ON "ubec_main"."ubec_sync_status" USING btree ("element");
CREATE INDEX IF NOT EXISTS "ix_ubec_sync_status_status" ON "ubec_main"."ubec_sync_status" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_ubec_sync_status_token_code" ON "ubec_main"."ubec_sync_status" USING btree ("token_code");
CREATE INDEX IF NOT EXISTS "ix_ubec_sync_status_sync_type" ON "ubec_main"."ubec_sync_status" USING btree ("sync_type");
CREATE INDEX IF NOT EXISTS "ix_ubec_sync_status_updated_at" ON "ubec_main"."ubec_sync_status" USING btree ("updated_at");

-- ============================================================
-- Reconstruction notes (40 fidelity flags)
-- NOT reconstructed from this document (absent in source):
--   * custom type / enum definitions  * function bodies
--   * view definitions               * trigger creation
--   * row data (incl. system_configuration seed)
-- ------------------------------------------------------------
-- FLAG: ubec_main.account_order_positions.asset_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.liquidity_pool_owners.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.liquidity_pool_owners.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.liquidity_pools.primary_element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.liquidity_pools.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.orderbook_analytics.asset_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.orderbook_snapshots.asset_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_accounts.primary_element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_accounts.token_holdings: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.stellar_effects.effect_element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_effects.asset_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_offers.selling_asset: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_operations.operation_element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_operations.asset_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_operations.type: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_transactions.primary_element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.stellar_transactions.involves_tokens: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformation_phases.target_outcomes: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformation_phases.participating_agents: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformative_actions.action_type: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.transformative_actions.impact_scale: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.transformative_actions.verifier_ids: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformative_actions.evidence_urls: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformative_actions.tags: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.transformative_actions.related_actions: ARRAY element type unknown; reconstructed as text[]
-- FLAG: ubec_main.ubec_audit_log.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_audit_log.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_balances.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_balances.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_balances.distribution_category: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_distributions.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_distributions.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_distributions.category: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_holonic_metrics.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_holonic_metrics.principle: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_holonic_metrics.health_status: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_reports.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_reports.token_code: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_sync_status.element: USER-DEFINED custom type reconstructed as text
-- FLAG: ubec_main.ubec_sync_status.token_code: USER-DEFINED custom type reconstructed as text
-- ============================================================
